server:
    port: 8080
    address: localhost

logging:
    level:
        com.github.izhangzhihao : debug

spring:
    datasource:
        name: SpringMVCSeedProject
        url: jdbc:mysql://localhost:3306/SpringMVCSeedProject?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
        username: root
        password:
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
        view:
            prefix: /templates/
            suffix: .jsp
mybatis:
  type-aliases-package: com.github.izhangzhihao.SSMSeedProject.Model

